[[redirects]]
  from = "/api/*"
  to = "http://ec2-3-15-168-58.us-east-2.compute.amazonaws.com:3000/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true